**Rahul Varma Chintalapati**

In [ ]:
#### Developed by Rahul Varma Chintalapati
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
df=pd.read_csv("/content/sample_data/churn.csv")
df.head()

churn  accountlength  ... totalintlcharge numbercustomerservicecalls
0    No            128  ...            2.70                          1
1    No            107  ...            3.70                          1
2    No            137  ...            3.29                          0
3    No             84  ...            1.78                          2
4    No             75  ...            2.73                          3

[5 rows x 18 columns]

In [ ]:
y=df.iloc[:,0].values
x=df.iloc[:,1:].values
print(x)
print(y)

[[128 'no' 'yes' ... 3 2.7 1]
 [107 'no' 'yes' ... 3 3.7 1]
 [137 'no' 'no' ... 5 3.29 0]
 ...
 [61 'no' 'no' ... 4 3.67 1]
 [109 'no' 'no' ... 6 2.3 0]
 [86 'no' 'yes' ... 16 2.51 0]]
['No' 'No' 'No' ... 'No' 'No' 'No']


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# from sklearn.preprocessing import OneHotEncoder# we use this when we cannot add values to the categorical values.

In [ ]:
le=LabelEncoder()# to transform the target variable
y= le.fit_transform(y)
print(y)

[0 0 0 ... 0 0 0]


In [ ]:
#from sklearn.compose import ColumnTransformer
# one=OneHotEncoder(drop="first")
le_x=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[128 0 1 ... 3 2.7 1]
 [107 0 1 ... 3 3.7 1]
 [137 0 0 ... 5 3.29 0]
 ...
 [61 0 0 ... 4 3.67 1]
 [109 0 0 ... 6 2.3 0]
 [86 0 1 ... 16 2.51 0]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:

print(x_train[0:5])

[[141 0 1 28 308.0 123 52.36 247.8 128 21.06 152.9 103 6.88 7.4 3 2.0 1]
 [135 0 0 0 239.9 91 40.78 177.1 104 15.05 217.2 118 9.77 5.9 3 1.59 2]
 [172 0 1 47 274.9 102 46.73 186.6 118 15.86 245.0 123 11.03 8.8 2 2.38 1]
 [54 0 1 24 92.3 88 15.69 193.1 98 16.41 99.3 119 4.47 11.6 3 3.13 2]
 [40 0 0 0 115.7 105 19.67 127.8 113 10.86 107.5 91 4.84 9.3 6 2.51 1]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=35, activation='relu'))
ann.add(tf.keras.layers.Dense(units=35, activation='relu'))
ann.add(tf.keras.layers.Dense(units=35, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))
opt = tf.keras.optimizers.Adam(learning_rate=0.001)
ann.compile(optimizer = opt, loss = 'mean_absolute_error', metrics = ['accuracy'])

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)
# from keras.callbacks import CSVLogger
# csv_logger = CSVLogger("model_history_log.csv", append=True)
# ann.fit_generator(x_train, y_train, batch_size = 32, epochs = 100,callbacks=[csv_logger])

Epoch 1/100
110/110 [==============================] - 1s 3ms/step - loss: 0.2212 - accuracy: 0.8509
Epoch 2/100
110/110 [==============================] - 0s 2ms/step - loss: 0.1681 - accuracy: 0.8557
Epoch 3/100
110/110 [==============================] - 0s 2ms/step - loss: 0.1542 - accuracy: 0.8634
Epoch 4/100
110/110 [==============================] - 0s 3ms/step - loss: 0.1397 - accuracy: 0.8831
Epoch 5/100
110/110 [==============================] - 0s 2ms/step - loss: 0.1300 - accuracy: 0.8989
Epoch 6/100
110/110 [==============================] - 0s 3ms/step - loss: 0.1254 - accuracy: 0.9006
Epoch 7/100
110/110 [==============================] - 0s 2ms/step - loss: 0.1193 - accuracy: 0.9029
Epoch 8/100
110/110 [==============================] - 0s 2ms/step - loss: 0.1162 - accuracy: 0.9046
Epoch 9/100
110/110 [==============================] - 0s 3ms/step - loss: 0.1130 - accuracy: 0.9057
Epoch 10/100
110/110 [==============================] - 0s 3ms/step - loss: 0.1088 - accura

In [ ]:

y_pred=ann.predict(x_test)
y_pred=y_pred>0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
sm=confusion_matrix(y_test,y_pred)
print(sm)
accuracy_score(y_test,y_pred)

[[1280   18]
 [  68  134]]


0.9426666666666667

In [ ]:
#print(ann.trainable_variables) 
weights=ann.trainable_variables
print(weights)

[<tf.Variable 'dense_36/kernel:0' shape=(17, 35) dtype=float32, numpy=
array([[ 2.30992049e-01,  3.92830372e-01,  1.41549170e-01,
         1.19312979e-01,  2.77320072e-02, -9.24788341e-02,
         1.71066672e-01,  2.13164344e-01,  6.81141019e-02,
        -9.34915394e-02, -2.27422081e-02,  4.59666438e-02,
         5.26493229e-02,  1.81887988e-02, -2.01496989e-01,
        -2.75525283e-02,  2.24177632e-02,  1.01283625e-01,
         7.25593567e-02, -2.37599984e-01,  2.15431765e-01,
        -4.52848151e-02, -6.97832033e-02,  2.27818370e-01,
        -1.23218305e-01,  2.49885961e-01, -2.56238192e-01,
         2.06105009e-01,  5.28039187e-02,  1.52577281e-01,
         2.04400182e-01,  2.90899575e-01, -1.87213644e-02,
        -1.76485583e-01,  1.66108713e-01],
       [-3.17984492e-01,  2.37577483e-01,  1.12679683e-01,
         5.54797947e-02,  2.12264642e-01,  1.10269591e-01,
        -4.90552366e-01, -2.87209570e-01, -5.20183966e-02,
        -2.82388210e-01,  2.05647990e-01, -3.96600008e-01,
 

In [ ]:
# error_surface = np.reshape(np.array(errors), (x_range.shape[0], y_range.shape[0]))
# _X, _Y = np.meshgrid(x_range, y_range, indexing='ij')

In [ ]:
from numpy import savetxt
savetxt('weights.csv', weights[0], delimiter=',')

In [ ]:
w1=pd.read_csv('weights.csv')

In [ ]:
w1.head()

NameError: ignored

In [ ]:
len(w1)

16